"""add home_layout column to sites

Revision ID: 0fd484b8d259
Revises: 704f4e95f8bf
Create Date: 2026-05-17 14:33:30.981698

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd484b8d259'
down_revision: str | Sequence[str] | None = '704f4e95f8bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('home_layout', sa.Text(), server_default=sa.text("'page'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'home_layout')
    # ### end Alembic commands ###
