"""initial schema

Revision ID: 704f4e95f8bf
Revises: 
Create Date: 2026-05-17 07:14:32.450571

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704f4e95f8bf'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_url', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('change_pwd_token', sa.Text(), nullable=True),
    sa.Column('security', sa.Text(), nullable=True),
    sa.Column('show_primer', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('partner', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_public_url'), 'sites', ['public_url'], unique=False)
    op.create_index(op.f('ix_sites_secret_url'), 'sites', ['secret_url'], unique=False)
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('header_color', sa.Text(), nullable=True),
    sa.Column('title_color', sa.Text(), nullable=True),
    sa.Column('title_font', sa.Text(), nullable=True),
    sa.Column('title_size', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('subtitle_color', sa.Text(), nullable=True),
    sa.Column('subtitle_font', sa.Text(), nullable=True),
    sa.Column('subtitle_size', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('content_font', sa.Text(), nullable=True),
    sa.Column('content_size', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('headings_font', sa.Text(), nullable=True),
    sa.Column('headings_size', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('hue', sa.Text(), nullable=True),
    sa.Column('brightness', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designs_site_id'), 'designs', ['site_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('caret_pos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scroll_pos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='pages_site_id_name_key')
    )
    op.create_index(op.f('ix_pages_site_id'), 'pages', ['site_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_page_id'), 'revisions', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_page_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_pages_site_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_designs_site_id'), table_name='designs')
    op.drop_table('designs')
    op.drop_index(op.f('ix_sites_secret_url'), table_name='sites')
    op.drop_index(op.f('ix_sites_public_url'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
